-- GAP-1: Soporte multi-región por usuario
CREATE TABLE USUARIO_REGION (
  IDUSUARIO  NUMBER        NOT NULL,
  IDREGION   NUMBER(2)     NOT NULL,
  CONSTRAINT PK_USUARIO_REGION PRIMARY KEY (IDUSUARIO, IDREGION),
  CONSTRAINT FK_UR_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
  CONSTRAINT FK_UR_REGION  FOREIGN KEY (IDREGION)  REFERENCES REGION(IDREGION)
);
