-- GAP-4: Historial de reprogramaciones
CREATE TABLE REPROGRAMACIONES_HIST (
  IDREPROG            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PRODUCTO_IDPRODUCTO NUMBER        NOT NULL,
  CUOTA_IDCUOTAS      NUMBER        NOT NULL,
  FCHREPROGRAMACION   DATE          NOT NULL,
  MONTOANTERIOR       NUMBER(15,2),
  MONTONUEVO          NUMBER(15,2),
  IDUSUARIO           NUMBER        NOT NULL,
  FCHREGISTRO         TIMESTAMP     DEFAULT SYSTIMESTAMP
);
