-- GAP-5: Tabla de auditoría de operaciones
CREATE TABLE AUDIT_LOG (
  IDAUDIT       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FCHOPERACION  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  IDUSUARIO     NUMBER,
  ENTIDAD       VARCHAR2(50)  NOT NULL,
  IDREGISTRO    VARCHAR2(100) NOT NULL,
  OPERACION     VARCHAR2(10)  NOT NULL,
  VALORANTERIOR CLOB,
  VALORNUEVO    CLOB,
  IPCLIENTE     VARCHAR2(45),
  ENDPOINT      VARCHAR2(200)
);
CREATE INDEX IDX_AUDIT_LOG_ENTIDAD ON AUDIT_LOG(ENTIDAD, IDREGISTRO);
CREATE INDEX IDX_AUDIT_LOG_USUARIO ON AUDIT_LOG(IDUSUARIO);
CREATE INDEX IDX_AUDIT_LOG_FECHA   ON AUDIT_LOG(FCHOPERACION);
